services:
  adcs-db-2:
    image: postgres:16-alpine
    container_name: adcs-db-2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adcs2026
      POSTGRES_DB: adcs_db_2
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      # dùng disk local EXT4
      - /var/lib/adcs/postgres:/var/lib/postgresql/data
    networks:
      - adcs_web_network

  adcs-backend:
    build:
      context: ./adcs-backend
    container_name: adcs-backend
    restart: always
    env_file:
      - ./adcs-backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:adcs2026@adcs-db-2:5432/adcs_db_2
    ports:
      - "12007:8000"
    volumes:
      - ./adcs-backend:/app 
      # giữ nguyên ổ lớn cho upload
      - /mnt/data2tb/adcs/uploads:/mnt/data2tb/adcs/uploads
    depends_on:
      - adcs-db-2
    networks:
      adcs_web_network:
        aliases:
          - backend

  adcs-frontend:
    build:
      context: ./adcs-frontend
    container_name: adcs-frontend
    restart: always
    env_file:
      - ./adcs-frontend/.env
    ports:
      - "12001:80"
    depends_on:
      - adcs-backend
    networks:
      - adcs_web_network

networks:
  adcs_web_network:
    driver: bridge