version: '3.8'

services:
  adcs-db-2:
    image: postgres:15-alpine
    container_name: adcs-db-2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adcs2026
      POSTGRES_DB: adcs_db_2
    ports:
      - "5433:5432"
    volumes:
      - adcs_db_2_data:/var/lib/postgresql/data
    networks:
      - adcs_web_network

  adcs-backend:
    build:
      context: ./adcs-backend
    container_name: adcs-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:adcs2026@adcs-db-2:5432/adcs_db_2
      - AI_SERVICE_URL=http://document-ai-service:8005
    ports:
      - "12010:8000"
    depends_on:
      - adcs-db-2
    networks:
      - adcs_web_network
      - document_ai_service_default

  adcs-frontend:
    build:
      context: ./adcs-frontend
    container_name: adcs-frontend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://203.162.88.102:12002/api/v1
    ports:
      - "12001:5173"
    depends_on:
      - adcs-backend
    networks:
      - adcs_web_network

networks:
  adcs_web_network:
    driver: bridge
  document_ai_service_default:
    external: true

volumes:
  adcs_db_2_data: